import type { Metadata } from "next";
import { RootProvider } from 'fumadocs-ui/provider/next';
import { Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type props = Readonly<{
  children: React.ReactNode;
}>

function RootLayout({ children }: props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex flex-col min-h-screen ${interSans.variable} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}

export default RootLayout
